## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: R
cache: packages

 include:
    r_github_packages:
      - marlonkobos/kuenm
